name: validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        python: [3.7, 3.9]

    runs-on: ubuntu-latest

    steps:
      - name: 🛑  Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️  Checkout repo
        uses: actions/checkout@v2

      - name: ⎔  Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: ⏭  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: ▶️ Run tests
        run: |
          pytest tests/test_*.py
